version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pooja123
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wp123

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wp123
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"  # Expose Nginx on port 80 of the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Ensure the path is correct and relative to the current directory
      - /var/log/nginx:/var/log/nginx  # Ensure this path exists on your host
    depends_on:
      - wordpress

volumes:
  wordpress_data:
  db_data: 
